
export const images = {
  allrock: require('../../../../assets/images/allrock.svg'),
  androidIconBackground: require('../../../../assets/images/android-icon-background.png'),
  androidIconForeground: require('../../../../assets/images/android-icon-foreground.png'),
  androidIconMonochrome: require('../../../../assets/images/android-icon-monochrome.png'),
  appearance: require('../../../../assets/images/appearance.png'),
  attach: require('../../../../assets/images/Attach.png'),
  back: require('../../../../assets/images/back.png'),
  backk: require('../../../../assets/images/backk.png'),
  batsticker: require('../../../../assets/images/batsticker.png'),
  binance: require('../../../../assets/images/Binance.png'),
  camera: require('../../../../assets/images/Camera.png'),
  checkMark: require('../../../../assets/images/check-mark.png'),
  check: require('../../../../assets/images/check.png'),
  coinBase: require('../../../../assets/images/CoinBase.png'),
  communications: require('../../../../assets/images/communications.png'),
  down: require('../../../../assets/images/down.png'),
  edit: require('../../../../assets/images/edit.png'),
  favicon: require('../../../../assets/images/favicon.png'),
  frame35: require('../../../../assets/images/Frame 35.png'),
  group: require('../../../../assets/images/Group.svg'),
  groupp: require('../../../../assets/images/Groupp.png'),
  groupp2: require('../../../../assets/images/Groupp2.png'),
  icon: require('../../../../assets/images/icon.png'),
  im1: require('../../../../assets/images/im1.jpg'),
  img1: require('../../../../assets/images/img1.jpg'),
  img2: require('../../../../assets/images/img2.jpg'),
  img3: require('../../../../assets/images/img3.jpg'),
  img4: require('../../../../assets/images/img4.jpg'),
  incoming: require('../../../../assets/images/incoming.png'),
  info: require('../../../../assets/images/Info.png'),
  jon: require('../../../../assets/images/jon.jpg'),
  language: require('../../../../assets/images/language.png'),
  martha: require('../../../../assets/images/Martha.png'),
  message: require('../../../../assets/images/message.png'),
  metamask: require('../../../../assets/images/metamask.png'),
  microphone: require('../../../../assets/images/microphone.png'),
  missedcall: require('../../../../assets/images/missedcall.png'),
  next: require('../../../../assets/images/next.png'),
  notification: require('../../../../assets/images/notification.png'),
  num17: require('../../../../assets/images/num17.png'),
  outgoing: require('../../../../assets/images/outgoing.png'),
  oval: require('../../../../assets/images/Oval.png'),
  partialReactLogo: require('../../../../assets/images/partial-react-logo.png'),
  pin: require('../../../../assets/images/pin.png'),
  plu: require('../../../../assets/images/plu.png'),
  plus: require('../../../../assets/images/plus.svg'),
  pluss: require('../../../../assets/images/pluss.png'),
  privacy: require('../../../../assets/images/privacy.png'),
  qrcode: require('../../../../assets/images/qrcode.png'),
  
  recentCalls: require('../../../../assets/images/recentCalls.png'),
  rock: require('../../../../assets/images/rock.svg'),
  rockk: require('../../../../assets/images/rockk.png'),
  rockk2: require('../../../../assets/images/rockk2.png'),
  savedMessages: require('../../../../assets/images/savedMessages.png'),
  setting: require('../../../../assets/images/setting.png'),
  shape: require('../../../../assets/images/Shape.svg'),
  splashIcon: require('../../../../assets/images/splash-icon.png'),
  stickers: require('../../../../assets/images/stickers.png'),
  storage: require('../../../../assets/images/storage.png'),
  telephone: require('../../../../assets/images/telephone.png'),
  token1: require('../../../../assets/images/token1.png'),
  topup: require('../../../../assets/images/topup.png'),
  trustWallet: require('../../../../assets/images/TrustWallet.png'),
  user: require('../../../../assets/images/user.png'),
  video: require('../../../../assets/images/video.png'),
  videoo: require('../../../../assets/images/videoo.png'),
  wallet: require('../../../../assets/images/wallet.png'),
  ActiveSessions: require('../../../../assets/images/ActiveSessions.png'),
  BlockedUsers: require('../../../../assets/images/BlockedUsers.png'),
  FaceID: require('../../../../assets/images/FaceID.png'),
  TwoStepVerification: require('../../../../assets/images/Two-StepVerification.png'),
  greenti:require('../../../../assets/images/greenti.png'),
  blackti:require('../../../../assets/images/blackti.png')

};
